//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WaterRefillSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class viewClientMonthly
    {
        public string clientID { get; set; }
        public string Client { get; set; }
        public string DR { get; set; }
        public string Date { get; set; }
        public byte Quantity { get; set; }
        public Nullable<decimal> Payed { get; set; }
    }
}
